export const products = [
  {
    "slug": "breed-dry-dog-food",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347629/dogFood_ksds31.png",
    "stars": 5,
    "name": "Breed Dry Dog Food",
    "price": 100,
    "tag": "-40%",
    "numOfReviews": 35,
    "discountedPrice": 140,
    "description": "High-quality dry dog food specially formulated for specific breeds. Packed with essential nutrients to keep your pet healthy and strong.",
    "category": "Pet Supplies",
    "specialCategory": "Flash Sales"
  },
  {
    "slug": "canon-eos-dslr-camera",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347588/Camera_lkva3j.png",
    "stars": 5,
    "name": "CANON EOS DSLR Camera",
    "price": 360,
    "numOfReviews": 95,
    "tag": "New",
    "discountedPrice": 380,
    "description": "Capture stunning photos and videos with this versatile DSLR camera from Canon, offering excellent image quality and performance.",
    "category": "Electronics",
    "specialCategory": "Best Selling"
  },
  {
    "slug": "asus-fhd-gaming-laptop",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347729/Laptop_m63p40.png",
    "stars": 4,
    "name": "ASUS FHD Gaming Laptop",
    "price": 700,
    "numOfReviews": 325,
    "tag": "-30%",
    "discountedPrice": 910,
    "description": "Powerful gaming laptop with a Full HD display, high-end GPU, and fast processor to give you an immersive gaming experience.",
    "category": "Electronics",
    "specialCategory": "Flash Sales"
  },
  {
    "slug": "curology-product-set",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347626/Curology_dpnoua.png",
    "stars": 5,
    "name": "Curology Product Set",
    "price": 500,
    "numOfReviews": 145,
    "tag": "-20%",
    "discountedPrice": 600,
    "description": "Customized skincare regimen designed for your unique needs. Helps with acne, wrinkles, and other skin concerns.",
    "category": "Beauty & Skincare",
    "specialCategory": "Explore"
  },
  {
    "slug": "kids-electric-car",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347593/Car_qi5jaq.png",
    "stars": 4,
    "name": "Kids Electric Car",
    "price": 960,
    "numOfReviews": 67,
    "tag": "-10%",
    "discountedPrice": 1056,
    "description": "A fun, battery-powered electric car for kids, offering hours of entertainment and outdoor play. Comes with safety features for peace of mind.",
    "category": "Toys & Games",
    "specialCategory": "Best Selling"
  },
  {
    "slug": "jr-zoom-soccer-cleats",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347608/Cleats_nahfff.png",
    "stars": 4,
    "name": "Jr. Zoom Soccer Cleats",
    "price": 320,
    "numOfReviews": 32,
    "tag": "",
    "discountedPrice": 350,
    "description": "High-performance soccer cleats designed for young athletes. Provides excellent traction and comfort for the best play on the field.",
    "category": "Sports & Outdoors",
    "specialCategory": "Explore"
  },
  {
    "slug": "gp11-shooter-usb-gamepad",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347632/Gamepad_cqxvly.png",
    "stars": 4,
    "name": "GP11 Shooter USB Gamepad",
    "price": 210,
    "numOfReviews": 78,
    "tag": "-30%",
    "discountedPrice": 273,
    "description": "Ergonomic USB gamepad designed for shooter games. Offers precision controls and comfortable gameplay for hours of fun.",
    "category": "Electronics",
    "specialCategory": "Flash Sales"
  },
  {
    "slug": "quilted-satin-jacket",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347738/Quilted_y3s7pp.png",
    "stars": 5,
    "name": "Quilted Satin Jacket",
    "price": 599,
    "numOfReviews": 91,
    "tag": "",
    "discountedPrice": 629,
    "description": "Stylish quilted satin jacket that offers both warmth and luxury. Perfect for chilly evenings or adding a touch of elegance to your wardrobe.",
    "category": "Fashion",
    "specialCategory": "Explore"
  },
  {
    "slug": "product-a-bag",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347570/bag_c509is.png",
    "stars": 3,
    "name": "Gucci duffle bag",
    "price": 10,
    "numOfReviews": 12,
    "discountedPrice": 15,
    "tag": "-50%",
    "description": "A versatile and affordable bag that’s perfect for everyday use, offering ample space and durability.",
    "category": "Accessories",
    "specialCategory": "Best Selling"
  },
  {
    "slug": "rain-coat",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347716/jacket_bwmnew.png",
    "stars": 4,
    "name": "Rain Coat",
    "price": 40,
    "numOfReviews": 22,
    "discountedPrice": 48,
    "tag": "-20%",
    "description": "Comfortable and stylish jacket perfect for cooler weather, offering a casual yet fashionable look.",
    "category": "Fashion",
    "specialCategory": "Explore"
  },
  {
    "slug": "product-e-monitor",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347734/monitor_bawbru.png",
    "stars": 4,
    "name": "IPS LCD Gaming Monitor",
    "price": 50,
    "numOfReviews": 58,
    "discountedPrice": 65,
    "tag": "",
    "description": "Affordable and compact monitor with great resolution, ideal for home offices or casual gaming setups.",
    "category": "Electronics",
    "specialCategory": "Flash Sales"
  },
  {
    "slug": "kitchen-chair",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347600/chair_cjchjd.png",
    "stars": 5,
    "name": "Kitchen Chair",
    "price": 120,
    "numOfReviews": 42,
    "discountedPrice": 130,
    "tag": "",
    "description": "Ergonomic gaming chair designed for long hours of comfort and support. Adjustable and sleek, perfect for gaming or work.",
    "category": "Furniture",
    "specialCategory": "Flash Sales"
  },
  {
    "slug": "cooler",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347618/cooler_wlrrm0.png",
    "stars": 4,
    "name": "RGB liquid CPU Cooler",
    "price": 89,
    "numOfReviews": 55,
    "discountedPrice": 95,
    "tag": "",
    "description": "Portable cooler with spacious capacity to keep your drinks and snacks fresh on the go. Ideal for outdoor adventures.",
    "category": "Outdoor Gear",
    "specialCategory": "Best Selling"
  },
  {
    "slug": "flash-joystick",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347719/joystickFlash_iu80fa.png",
    "stars": 4,
    "name": "HAVIT HV-G92 Gamepad",
    "price": 50,
    "numOfReviews": 38,
    "discountedPrice": 57.5,
    "tag": "-15%",
    "description": "A high-quality joystick for gaming enthusiasts, featuring responsive controls and smooth gameplay experience.",
    "category": "Electronics",
    "specialCategory": "Flash Sales"
  },
  {
    "slug": "mechanical-keyboard",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347724/keyboard_ya3q0n.png",
    "stars": 5,
    "name": "AK-900 Wired Keyboard",
    "price": 95,
    "numOfReviews": 105,
    "discountedPrice": 104.5,
    "tag": "-10%",
    "description": "A durable mechanical keyboard designed for fast typists and gamers, with customizable RGB lighting and responsive keys.",
    "category": "Electronics",
    "specialCategory": "Explore"
  },
  {
    "slug": "shelf",
    "image": "https://res.cloudinary.com/dvsuhy8uh/image/upload/v1741347742/shelf_u3cg5c.png",
    "stars": 4,
    "name": "Small BookShelf",
    "price": 70,
    "numOfReviews": 27,
    "discountedPrice": 75,
    "tag": "",
    "description": "Stylish and functional wooden shelf perfect for any room, offering plenty of space for books, plants, or decor.",
    "category": "Furniture",
    "specialCategory": "Best Selling"
  }
];
